language: php

php:
    - 7.2
    - 7.4

env:
    global:
        - DEFAULT=1

matrix:
    include:
        - php: 7.2
          env: VALIDATION=1 DEFAULT=0

        - php: 7.4
          env: VALIDATION=1 DEFAULT=0

    fast_finish: true

    allow_failures:
        - php: 7.2
        - php: 7.4

before_install:
    - phpenv config-add ci/travis.php.ini

before_script:
    - phpenv config-rm xdebug.ini
    - composer install --prefer-dist --no-interaction

script:
    - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept run ; fi
    - if [[ $VALIDATION == 1 ]]; then composer cs-check ; fi
    - if [[ $VALIDATION == 1 ]]; then composer phpstan-setup && composer phpstan ; fi

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
